- menu_name: "Services"

- name: "Centro Médico Juan Pablo II"
  url: "/centromedicojuanpabloii.com/"
  title: "Al Servicio de los Tilaranenses"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
